### ISSUE TITLE
React to retry-after?

### ISSUE THREAD

**Issue by onli** [zombocom/rate_throttle_client#10]
Great idea for a gem! 

Some APIs set a retry-after header on 429 responses, for example Reddit returns this when requesting RSS feed as a bot:

```
{"connection"=>["close"], "content-length"=>["1064"], "content-type"=>["application/atom+xml; charset=UTF-8"], "x-ua-compatible"=>["IE=edge"], "retry-after"=>["9"], "x-frame-options"=>["SAMEORIGIN"], "x-content-type-options"=>["nosniff"], "x-xss-protection"=>["1; mode=block"], "cache-control"=>["max-age=0, must-revalidate"], "x-moose"=>["majestic"], "accept-ranges"=>["bytes"], "date"=>["Wed, 15 Jul 2020 10:50:01 GMT"], "via"=>["1.1 varnish"], "x-served-by"=>["cache-lon4270-LON"], "x-cache"=>["MISS"], "x-cache-hits"=>["0"], "x-timer"=>["S1594810201.463055,VS0,VE201"], "set-cookie"=>["session_tracker=...; Domain=reddit.com; Max-Age=7199; Path=/; expires=Wed, 15-Jul-2020 12:50:01 GMT; secure; SameSite=None; Secure", "csv=1; Max-Age=63072000; Domain=.reddit.com; Path=/; Secure; SameSite=None", "edgebucket=iICej9HBbYQrINnYmL; Domain=reddit.com; Max-Age=63071999; Path=/;  secure"], "strict-transport-security"=>["max-age=15552000; includeSubDomains; preload"], "server"=>["snooserv"]}
```

It can be either a wait time in seconds or a date, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After.

It could be a nice extension of the provided strategies to react to that header to avoid unnecessary retries.

**Comment by schneems** [comment]
All client strategies are currently written to handle GCRA. If an API is returning a `retry-after` then it's likely using a "leaky bucket" rate-limit server strategy. 

In general leaky bucket is really easy to handle as a rate throttle client, but it provides non-optimal load on the server since it doesn't encourage people to spread out their load. There's really no incentive for a client to not just spam requests as fast as possible until it hits the limit and has to sleep.

In that case none of the existing client rate-throttle strategies would be suited for leaky bucket. 

The strategy that would work would look like this:

- Make an API request
- On 429 sleep until the specified time with possibly some jitter
- Retry the request

It's fairly straight-forward. If you want to make a generic strategy to handle this case, I would accept a PR. It would go in https://github.com/zombocom/rate_throttle_client/tree/master/lib/rate_throttle_client/clients, it might be named "leaky_bucket".

**Comment by onli** [comment]
Hi @schneems, thanks for your answer. 

> There's really no incentive for a client to not just spam requests as fast as possible until it hits the limit and has to sleep.

There is one, because at least in this scenario you get more data out of the API if you do not provoke a 429 response in the first place, with its several seconds wait time. And you risk a manual ban.

The strategy you describe is exactly how my client handles it already, so I evidently agree :)

The complication are things like the "only 1 request each 2 seconds", trying to use the bucket without tripping the 429 response - but the strategy could use `min_sleep` for that, right? But well, that only makes sense if you make more than 1 request. I'm not sure this gem is the right layer for that usage?

I would then now try to prepare the PR next.

**Comment by schneems** [comment]
> There is one, because at least in this scenario you get more data out of the API if you do not provoke a 429 response in the first place

Interesting, do you know any providers that have a leaky bucket with a penalty like that for hitting 0 available requests?

**Comment by onli** [comment]
Yes, reddit! :) Don't have another example at hand, but this cool off period does not look that strange to me.

**Comment by schneems** [comment]
I'm looking at the reddit API docs and this is what I found:

```
Clients connecting via OAuth2 may make up to 60 requests per minute. Monitor the following response headers to ensure that you're not exceeding the limits:

    X-Ratelimit-Used: Approximate number of requests used in this period
    X-Ratelimit-Remaining: Approximate number of requests left to use
    X-Ratelimit-Reset: Approximate number of seconds to end of period
```

From: https://github.com/reddit-archive/reddit/wiki/API but it's marked as "archived". I found it from https://www.reddit.com/dev/api which seams cannonical.

**Comment by schneems** [comment]
Cleaning issues. I need more info on a production API that exhibits this behavior along with detailed docs on how it's implemented so I can make a simulated server. I'm happy to support additional server types, but not speculatively. It needs to be a real and valid use case.
